[package]
name = "sparslog"
version = "0.1.8"
edition = "2024"
license = "MIT"
authors = ["Thomas Habets <thomas@habets.se>"]
readme = "README.md"
repository = "https://github.com/ThomasHabets/sparslog"
description = "SDR receiver for IKEA sparsnäs"
keywords = ["SDR", "ikea"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
ctrlc = "3"
log = "0.4"
num = "0.4"
# `unstable` to enable IQ streaming to a UI.
rustradio = {version="0.18.6", features=["rtlsdr", "fast-math", "async", "unstable"]}
stderrlog = "0.6"
clap = {version = "4", features = ["derive"]}
console-subscriber = "0.4.1"
tokio = "1.45.0"
prometheus = { version = "0.14.0", features = ["process", "push"] }

[dev-dependencies]
tempfile = "3"

[features]
default = []
volk = ["rustradio/volk"]
tokio-unstable = ["tokio/tracing", "rustradio/tokio-unstable"]

[[bin]]
name = "sparslog"
path = "src/main.rs"

[[bin]]
name = "sparslog-async"
path = "src/main_async.rs"

[lib]
path = "src/sparslog.rs"

[patch.crates-io]
#rustradio = { path = "../rustradio" }
